import json
from pathlib import Path
from datetime import date

OUTPUT_PATH = Path("data/source_registry.json")

TODAY = str(date.today())


def quality_controls(review=False):
    return {
        "requires_snapshot": True,
        "requires_metadata": True,
        "requires_deduplication": True,
        "allow_llm_extraction": True,
        "requires_human_review": review
    }


def make_source(
    idx,
    name,
    family,
    source_type,
    tier,
    url,
    purpose,
    entities,
    themes,
    reliability,
    bias,
    license_status,
    collection_method,
    active_status,
    refresh,
    formats,
    priority,
    downstream,
    notes=""
):
    root_domain = url.replace("https://", "").replace("http://", "").split("/")[0]

    return {
        "source_id": f"src_{idx:03d}",
        "source_name": name,
        "source_family": family,
        "source_type": source_type,
        "source_tier": tier,
        "url": url,
        "root_domain": root_domain,
        "purpose": purpose,
        "associated_entities": entities,
        "themes": themes,
        "reliability_score": reliability,
        "bias_risk": bias,
        "license_status": license_status,
        "collection_method": collection_method,
        "active_status": active_status,
        "refresh_frequency": refresh,
        "content_formats": formats,
        "ingestion_priority": priority,
        "downstream_use": downstream,
        "quality_controls": quality_controls(
            review=source_type in ["news_article", "trade_publication", "manual_document", "patent_database", "job_postings"]
        ),
        "notes": notes,
        "last_reviewed_date": TODAY
    }


SOURCE_ROWS = [
    # =========================
    # TIER 0 — PRIMARY / REGULATORY
    # =========================
    (
        "Nvidia Investor Relations SEC Filings",
        "primary_regulatory",
        "sec_filing",
        0,
        "https://investor.nvidia.com/financial-info/sec-filings/default.aspx",
        "Authoritative Nvidia SEC filings for risk factors, financial disclosures, business dependencies, customer/supplier exposure, and regulatory context.",
        ["Nvidia"],
        ["risk_factors", "financial_performance", "export_controls", "china_restrictions", "supplier_dependency"],
        0.96,
        "low",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "risk_detection", "confidence_scoring", "dossier_generation"],
        "Highest-priority Nvidia source."
    ),
    (
        "Nvidia Annual Reports and Proxies",
        "primary_regulatory",
        "annual_report",
        0,
        "https://investor.nvidia.com/financial-info/annual-reports-and-proxies/default.aspx",
        "Official annual reports and proxy materials for long-form strategy, risk, market exposure, governance, and business context.",
        ["Nvidia"],
        ["risk_factors", "financial_performance", "data_center_growth", "supplier_dependency", "export_controls"],
        0.96,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "annual",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "risk_detection", "dossier_generation", "relationship_discovery"],
        "Use latest annual report early."
    ),
    (
        "SEC EDGAR Nvidia Company Page",
        "primary_regulatory",
        "sec_filing",
        0,
        "https://www.sec.gov/edgar/browse/?CIK=1045810",
        "Direct SEC filing archive for Nvidia CIK 1045810, used as regulator-controlled source of truth.",
        ["Nvidia"],
        ["risk_factors", "financial_performance", "regulatory_context", "export_controls"],
        0.98,
        "low",
        "official_public",
        "scripted_fetch",
        "active_now",
        "quarterly",
        ["html", "xbrl", "xml"],
        1,
        ["evidence_extraction", "source_validation", "confidence_scoring", "risk_detection"],
        "Use SEC-compliant user agent for scripted fetching."
    ),
    (
        "SEC Nvidia Submissions JSON",
        "primary_regulatory",
        "sec_filing",
        0,
        "https://data.sec.gov/submissions/CIK0001045810.json",
        "Machine-readable Nvidia SEC submissions index for discovering 10-K, 10-Q, 8-K and other filings.",
        ["Nvidia"],
        ["financial_performance", "risk_factors", "regulatory_context"],
        0.98,
        "low",
        "official_public",
        "api",
        "active_now",
        "daily",
        ["json"],
        1,
        ["source_validation", "evidence_extraction", "confidence_scoring"],
        "Good for automated filing discovery."
    ),
    (
        "SEC Nvidia Company Facts XBRL",
        "primary_regulatory",
        "sec_filing",
        0,
        "https://data.sec.gov/api/xbrl/companyfacts/CIK0001045810.json",
        "Machine-readable Nvidia XBRL facts for structured financial validation.",
        ["Nvidia"],
        ["financial_performance", "data_center_growth"],
        0.98,
        "low",
        "official_public",
        "api",
        "active_later",
        "quarterly",
        ["json", "xbrl"],
        2,
        ["source_validation", "confidence_scoring", "dossier_generation"],
        "Useful after the first evidence pipeline works."
    ),
    (
        "BIS Export Controls",
        "regulatory_policy",
        "regulatory_export_control",
        0,
        "https://www.bis.gov/",
        "Official Bureau of Industry and Security source for export-control policy affecting advanced AI chips and semiconductor equipment.",
        ["Nvidia", "BIS", "China"],
        ["export_controls", "china_restrictions", "regulatory_context", "risk_factors"],
        0.95,
        "low",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html", "pdf"],
        1,
        ["risk_detection", "evidence_extraction", "watch_item_generation", "confidence_scoring"],
        "Use specific BIS pages after discovery."
    ),
    (
        "Federal Register Export-Control Rules",
        "regulatory_policy",
        "government_rule",
        0,
        "https://www.federalregister.gov/documents/search?conditions%5Bterm%5D=advanced+computing+semiconductor+export+controls",
        "Official legal source for export-control rules affecting advanced computing and semiconductor supply chains.",
        ["Nvidia", "BIS", "China"],
        ["export_controls", "china_restrictions", "regulatory_context", "risk_factors"],
        0.96,
        "low",
        "official_public",
        "scripted_fetch",
        "active_now",
        "event_driven",
        ["html", "pdf", "xml"],
        1,
        ["risk_detection", "evidence_extraction", "watch_item_generation", "confidence_scoring"],
        "Search page; ingest exact rules after discovery."
    ),

    # =========================
    # TIER 1 — INVESTOR / MANAGEMENT SIGNALS
    # =========================
    (
        "Nvidia Quarterly Results",
        "company_investor",
        "quarterly_result",
        1,
        "https://investor.nvidia.com/financial-info/quarterly-results/default.aspx",
        "Official quarterly results for revenue mix, data center growth, margin commentary, guidance, and near-term signals.",
        ["Nvidia"],
        ["financial_performance", "data_center_growth", "ai_accelerators", "hyperscaler_demand"],
        0.90,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "event_detection", "dossier_generation"],
        "High signal for current performance."
    ),
    (
        "Nvidia Financial Reports",
        "company_investor",
        "earnings_release",
        1,
        "https://investor.nvidia.com/financial-info/financial-reports/default.aspx",
        "Official earnings releases and financial reports for structured financial and segment-level evidence.",
        ["Nvidia"],
        ["financial_performance", "data_center_growth", "ai_accelerators"],
        0.90,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "event_detection", "dossier_generation"],
        "Use with quarterly results."
    ),
    (
        "Nvidia Events and Presentations",
        "company_investor",
        "investor_presentation",
        1,
        "https://investor.nvidia.com/events-and-presentations/events-and-presentations/default.aspx",
        "Investor presentations and event materials for management messaging, product roadmap, and market positioning.",
        ["Nvidia"],
        ["blackwell", "data_center_growth", "ai_accelerators", "cuda_ecosystem", "partnership"],
        0.86,
        "medium",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "event_detection", "relationship_discovery", "dossier_generation"],
        "Company-controlled but strategically useful."
    ),
    (
        "Reuters Technology News",
        "market_news",
        "news_article",
        1,
        "https://www.reuters.com/technology/",
        "Trusted external news for validation of Nvidia, supplier, hyperscaler, export-control, and semiconductor events.",
        ["Nvidia", "TSMC", "SK Hynix", "Micron", "AMD"],
        ["competitor_movement", "supplier_dependency", "hbm_supply", "export_controls", "industry_context"],
        0.84,
        "medium",
        "licensed_required",
        "restricted_manual_only",
        "restricted",
        "event_driven",
        ["html"],
        4,
        ["source_validation", "event_detection", "graph_context"],
        "Do not scrape automatically unless licensed."
    ),

    # =========================
    # TIER 2 — NVIDIA-CONTROLLED SOURCES
    # =========================
    (
        "Nvidia Newsroom",
        "company_news",
        "company_newsroom",
        2,
        "https://nvidianews.nvidia.com/",
        "Official Nvidia announcements, partnerships, launches, and company narrative for event discovery.",
        ["Nvidia"],
        ["product_launch", "partnership", "blackwell", "data_center_growth"],
        0.78,
        "medium_high",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html"],
        1,
        ["evidence_extraction", "event_detection", "relationship_discovery", "watch_item_generation"],
        "Company-controlled; source weight lower than filings."
    ),
    (
        "Nvidia Latest News",
        "company_news",
        "press_release",
        2,
        "https://nvidianews.nvidia.com/news/latest",
        "Latest official Nvidia announcements for product, partnership, and ecosystem event detection.",
        ["Nvidia"],
        ["product_launch", "partnership", "ai_accelerators", "blackwell"],
        0.78,
        "medium_high",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html"],
        1,
        ["evidence_extraction", "event_detection", "relationship_discovery", "watch_item_generation"],
        "Good for recent company-controlled signals."
    ),
    (
        "Nvidia Blackwell Platform Announcement",
        "company_news",
        "press_release",
        2,
        "https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing",
        "Official Blackwell platform announcement for AI accelerator roadmap and product positioning evidence.",
        ["Nvidia"],
        ["blackwell", "ai_accelerators", "product_launch", "data_center_growth"],
        0.78,
        "medium_high",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html"],
        1,
        ["evidence_extraction", "event_detection", "relationship_discovery"],
        "Important product strategy source."
    ),
    (
        "Nvidia Data Center Products",
        "company_product",
        "product_page",
        2,
        "https://www.nvidia.com/en-us/data-center/products/",
        "Official data center product portfolio for mapping GPUs, systems, networking, and AI factory offerings.",
        ["Nvidia"],
        ["data_center_growth", "ai_accelerators", "blackwell", "product_launch"],
        0.76,
        "medium_high",
        "official_public",
        "manual_download",
        "active_now",
        "monthly",
        ["html"],
        2,
        ["evidence_extraction", "relationship_discovery", "graph_context"],
        "Useful for product/entity mapping."
    ),
    (
        "Nvidia CUDA Toolkit",
        "company_technical",
        "developer_docs",
        2,
        "https://developer.nvidia.com/cuda-toolkit",
        "Official CUDA source for software ecosystem, developer lock-in, and platform strength evidence.",
        ["Nvidia"],
        ["cuda_ecosystem", "ai_accelerators"],
        0.76,
        "medium_high",
        "official_public",
        "manual_download",
        "active_now",
        "monthly",
        ["html"],
        2,
        ["evidence_extraction", "relationship_discovery", "graph_context"],
        "Important for Nvidia software moat."
    ),
    (
        "Nvidia Documentation Hub",
        "company_technical",
        "developer_docs",
        2,
        "https://docs.nvidia.com/",
        "Official technical documentation hub for CUDA, networking, deployment, and product documentation.",
        ["Nvidia"],
        ["cuda_ecosystem", "ai_accelerators", "blackwell"],
        0.74,
        "medium_high",
        "official_public",
        "manual_download",
        "active_later",
        "monthly",
        ["html"],
        3,
        ["graph_context", "watch_item_generation", "evidence_extraction"],
        "Use selectively; too broad for first ingestion."
    ),
    (
        "Nvidia Careers",
        "jobs_hiring",
        "job_postings",
        2,
        "https://www.nvidia.com/en-us/about-nvidia/careers/",
        "Official hiring source for weak signals around supply chain, CUDA, systems, networking, and infrastructure focus.",
        ["Nvidia"],
        ["hiring_signal", "cuda_ecosystem", "supplier_dependency"],
        0.68,
        "medium_high",
        "official_public",
        "web_snapshot",
        "active_later",
        "monthly",
        ["html"],
        4,
        ["watch_item_generation", "graph_context"],
        "Weak signal only."
    ),

    # =========================
    # TIER 3 — SUPPLIER / ECOSYSTEM / PARTNER SOURCES
    # =========================
    (
        "TSMC Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://investor.tsmc.com/english",
        "TSMC investor source for foundry capacity, capex, advanced nodes, and Nvidia manufacturing dependency context.",
        ["TSMC", "Nvidia"],
        ["foundry_dependency", "advanced_packaging", "supplier_dependency", "financial_performance"],
        0.86,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Critical supplier source."
    ),
    (
        "TSMC CoWoS 3DFabric",
        "supplier_ecosystem",
        "supplier_newsroom",
        3,
        "https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm",
        "Official CoWoS technology source for advanced packaging and HBM integration context around AI accelerators.",
        ["TSMC", "Nvidia", "HBM suppliers"],
        ["advanced_packaging", "hbm_supply", "foundry_dependency", "ai_accelerators"],
        0.84,
        "medium",
        "official_public",
        "manual_download",
        "active_now",
        "monthly",
        ["html"],
        1,
        ["evidence_extraction", "relationship_discovery", "graph_context"],
        "Critical for packaging dependency."
    ),
    (
        "SK hynix Newsroom",
        "supplier_ecosystem",
        "supplier_newsroom",
        3,
        "https://news.skhynix.com/",
        "Official SK hynix announcements for HBM supply, HBM3E/HBM4, memory roadmap, and AI demand.",
        ["SK Hynix", "Nvidia"],
        ["hbm_supply", "supplier_dependency", "ai_accelerators", "partnership"],
        0.84,
        "medium",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html"],
        1,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Critical HBM source."
    ),
    (
        "Micron Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://investors.micron.com/",
        "Micron investor source for HBM ramp, AI memory demand, capex, and supplier competition.",
        ["Micron", "Nvidia"],
        ["hbm_supply", "supplier_dependency", "financial_performance", "competitor_movement"],
        0.85,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Critical HBM supplier/competitor source."
    ),
    (
        "Micron Newsroom",
        "supplier_ecosystem",
        "supplier_newsroom",
        3,
        "https://www.micron.com/about/press/news",
        "Official Micron announcements for HBM, memory roadmap, product launches, and AI data center demand.",
        ["Micron", "Nvidia"],
        ["hbm_supply", "product_launch", "supplier_dependency", "ai_accelerators"],
        0.82,
        "medium",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html"],
        2,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Good for HBM movement."
    ),
    (
        "Samsung Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://www.samsung.com/global/ir/",
        "Samsung investor source for memory, foundry, capex, and supplier/competitor context.",
        ["Samsung", "Nvidia"],
        ["hbm_supply", "foundry_dependency", "competitor_movement", "financial_performance"],
        0.85,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        1,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Important memory/foundry source."
    ),
    (
        "Samsung Semiconductor News",
        "supplier_ecosystem",
        "supplier_newsroom",
        3,
        "https://semiconductor.samsung.com/news-events/news/",
        "Samsung semiconductor announcements for HBM, foundry, advanced packaging, and AI memory movement.",
        ["Samsung", "Nvidia"],
        ["hbm_supply", "foundry_dependency", "advanced_packaging", "product_launch"],
        0.82,
        "medium",
        "official_public",
        "manual_download",
        "active_later",
        "event_driven",
        ["html"],
        2,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Use after first HBM sources."
    ),
    (
        "ASML Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://www.asml.com/en/investors",
        "ASML investor source for lithography capacity and semiconductor equipment constraints affecting advanced-node supply.",
        ["ASML", "TSMC", "Samsung", "Nvidia"],
        ["supplier_dependency", "foundry_dependency", "industry_context", "financial_performance"],
        0.86,
        "low_medium",
        "official_public",
        "manual_download",
        "active_now",
        "quarterly",
        ["html", "pdf"],
        2,
        ["evidence_extraction", "relationship_discovery", "event_detection", "graph_context"],
        "Useful for equipment bottleneck context."
    ),
    (
        "ASE Technology Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://ir.aseglobal.com/",
        "ASE investor source for outsourced semiconductor assembly, test, and advanced packaging capacity context.",
        ["ASE", "Nvidia", "TSMC"],
        ["advanced_packaging", "supplier_dependency", "financial_performance"],
        0.82,
        "low_medium",
        "official_public",
        "manual_download",
        "active_later",
        "quarterly",
        ["html", "pdf"],
        3,
        ["relationship_discovery", "graph_context", "watch_item_generation"],
        "Advanced packaging ecosystem source."
    ),
    (
        "Amkor Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://ir.amkor.com/",
        "Amkor investor source for packaging and test capacity, advanced packaging, and OSAT industry signals.",
        ["Amkor", "Nvidia", "TSMC"],
        ["advanced_packaging", "supplier_dependency", "financial_performance"],
        0.82,
        "low_medium",
        "official_public",
        "manual_download",
        "active_later",
        "quarterly",
        ["html", "pdf"],
        3,
        ["relationship_discovery", "graph_context", "watch_item_generation"],
        "Advanced packaging ecosystem source."
    ),
    (
        "Broadcom Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://investors.broadcom.com/",
        "Broadcom investor source for custom AI accelerator, networking ASIC, and competitive movement against Nvidia.",
        ["Broadcom", "Nvidia"],
        ["competitor_movement", "ai_accelerators", "data_center_growth", "financial_performance"],
        0.84,
        "low_medium",
        "official_public",
        "manual_download",
        "active_later",
        "quarterly",
        ["html", "pdf"],
        2,
        ["relationship_discovery", "event_detection", "graph_context"],
        "Important competitor/custom silicon signal."
    ),
    (
        "AMD Investor Relations",
        "supplier_ecosystem",
        "supplier_investor_relations",
        3,
        "https://ir.amd.com/",
        "AMD investor source for GPU accelerator competition, data center strategy, and market movement versus Nvidia.",
        ["AMD", "Nvidia"],
        ["competitor_movement", "ai_accelerators", "data_center_growth", "financial_performance"],
        0.84,
        "low_medium",
        "official_public",
        "manual_download",
        "active_later",
        "quarterly",
        ["html", "pdf"],
        2,
        ["relationship_discovery", "event_detection", "graph_context"],
        "Main accelerator competitor."
    ),
    (
        "AWS and Nvidia Strategic Collaboration",
        "customer_partner",
        "customer_partner_announcement",
        3,
        "https://nvidianews.nvidia.com/news/aws-nvidia-strategic-collaboration-for-generative-ai",
        "Official AWS/Nvidia collaboration announcement for hyperscaler demand and partner relationship evidence.",
        ["Nvidia", "Amazon Web Services"],
        ["hyperscaler_demand", "partnership", "data_center_growth"],
        0.82,
        "medium_high",
        "official_public",
        "manual_download",
        "active_now",
        "event_driven",
        ["html"],
        1,
        ["relationship_discovery", "event_detection", "graph_context", "watch_item_generation"],
        "Useful for customer/partner graph."
    ),
    (
        "Oracle Cloud and Nvidia",
        "customer_partner",
        "customer_partner_announcement",
        3,
        "https://www.oracle.com/cloud/nvidia/",
        "Oracle/Nvidia cloud partnership page for OCI GPU demand, deployment options, and customer ecosystem evidence.",
        ["Oracle", "Nvidia"],
        ["hyperscaler_demand", "partnership", "data_center_growth"],
        0.80,
        "medium_high",
        "official_public",
        "manual_download",
        "active_later",
        "monthly",
        ["html"],
        2,
        ["relationship_discovery", "event_detection", "graph_context"],
        "Cloud customer/partner source."
    ),
    (
        "Dell AI Factory with Nvidia",
        "customer_partner",
        "customer_partner_announcement",
        3,
        "https://www.dell.com/en-us/lp/dt/nvidia-ai",
        "Dell/Nvidia AI Factory source for enterprise infrastructure channel and OEM/system integration relationships.",
        ["Dell", "Nvidia"],
        ["partnership", "data_center_growth", "hyperscaler_demand"],
        0.78,
        "medium_high",
        "official_public",
        "manual_download",
        "active_later",
        "monthly",
        ["html"],
        3,
        ["relationship_discovery", "event_detection", "graph_context"],
        "OEM/channel ecosystem source."
    ),
    (
        "HPE Nvidia AI Computing",
        "customer_partner",
        "customer_partner_announcement",
        3,
        "https://www.hpe.com/us/en/solutions/artificial-intelligence/nvidia-collaboration.html",
        "HPE/Nvidia source for enterprise AI factory, private cloud AI, and OEM channel relationship evidence.",
        ["HPE", "Nvidia"],
        ["partnership", "data_center_growth", "hyperscaler_demand"],
        0.78,
        "medium_high",
        "official_public",
        "manual_download",
        "active_later",
        "monthly",
        ["html"],
        3,
        ["relationship_discovery", "event_detection", "graph_context"],
        "OEM/channel ecosystem source."
    ),
    (
        "Supermicro Nvidia AI Factory",
        "customer_partner",
        "customer_partner_announcement",
        3,
        "https://www.supermicro.com/en/accelerators/nvidia/ai-factory",
        "Supermicro/Nvidia AI factory source for server ecosystem, channel demand, and system-integration evidence.",
        ["Supermicro", "Nvidia"],
        ["partnership", "data_center_growth", "hyperscaler_demand"],
        0.78,
        "medium_high",
        "official_public",
        "manual_download",
        "active_later",
        "monthly",
        ["html"],
        3,
        ["relationship_discovery", "event_detection", "graph_context"],
        "Server ecosystem source."
    ),

    # =========================
    # TIER 4 — BENCHMARK / PATENT / INDUSTRY CONTEXT / WEAK SIGNALS
    # =========================
    (
        "MLCommons MLPerf Training Benchmarks",
        "benchmark_technical",
        "benchmark",
        4,
        "https://mlcommons.org/benchmarks/training/",
        "Independent benchmark source for AI hardware performance comparisons and external validation of accelerator claims.",
        ["Nvidia", "AMD", "Google", "Intel"],
        ["benchmark_performance", "ai_accelerators", "competitor_movement"],
        0.78,
        "low_medium",
        "public",
        "manual_download",
        "active_later",
        "event_driven",
        ["html", "csv"],
        3,
        ["graph_context", "source_validation", "watch_item_generation", "evidence_extraction"],
        "Benchmark context; not business evidence alone."
    ),
    (
        "Google Patents Advanced Search",
        "patent_research",
        "patent_database",
        4,
        "https://patents.google.com/advanced",
        "Patent search source for Nvidia technology direction and R&D signals, used carefully as weak signal evidence.",
        ["Nvidia"],
        ["patents_r_and_d", "ai_accelerators", "cuda_ecosystem"],
        0.70,
        "medium",
        "public",
        "manual_only",
        "manual_only",
        "manual",
        ["html"],
        5,
        ["graph_context", "watch_item_generation"],
        "Manual-only until patent search strategy is defined."
    ),
    (
        "USPTO Patent Public Search",
        "patent_research",
        "patent_database",
        4,
        "https://ppubs.uspto.gov/pubwebapp/static/pages/landing.html",
        "Official patent source for Nvidia-assigned patents and R&D direction.",
        ["Nvidia"],
        ["patents_r_and_d", "ai_accelerators"],
        0.76,
        "low_medium",
        "public",
        "manual_only",
        "manual_only",
        "manual",
        ["html"],
        5,
        ["graph_context", "watch_item_generation"],
        "Manual-only for now."
    ),
    (
        "Semiconductor Industry Association Supply Chain Investments",
        "industry_context",
        "industry_association",
        4,
        "https://www.semiconductors.org/chip-supply-chain-investments/",
        "Industry association context for semiconductor supply-chain investments, CHIPS Act context, and ecosystem mapping.",
        ["Nvidia", "Semiconductor Industry"],
        ["industry_context", "supplier_dependency", "foundry_dependency"],
        0.74,
        "medium",
        "public",
        "manual_download",
        "active_later",
        "monthly",
        ["html"],
        4,
        ["graph_context", "source_validation", "watch_item_generation"],
        "Context only."
    ),
    (
        "JEDEC HBM Standards",
        "benchmark_technical",
        "industry_association",
        4,
        "https://www.jedec.org/standards-documents/focus/memory/hbm-high-bandwidth-memory-dram",
        "Standards context for HBM specifications, useful for interpreting memory roadmap and benchmark claims.",
        ["JEDEC", "HBM suppliers", "Nvidia"],
        ["hbm_supply", "benchmark_performance", "industry_context"],
        0.75,
        "low_medium",
        "public",
        "manual_download",
        "active_later",
        "monthly",
        ["html", "pdf"],
        4,
        ["graph_context", "source_validation", "watch_item_generation"],
        "Technical context source."
    ),
    (
        "Tom's Hardware Semiconductor Coverage",
        "market_news",
        "trade_publication",
        4,
        "https://www.tomshardware.com/tech-industry/semiconductors",
        "Technology trade publication for context on chips, GPUs, memory, packaging, and competitor movement.",
        ["Nvidia", "AMD", "Intel", "TSMC"],
        ["competitor_movement", "industry_context", "hbm_supply"],
        0.62,
        "medium_high",
        "public",
        "manual_download",
        "active_later",
        "event_driven",
        ["html"],
        5,
        ["graph_context", "source_validation", "watch_item_generation"],
        "Secondary context only."
    ),

    # =========================
    # TIER 5 — MANUAL / INTERNAL / CONTROLLED INPUTS
    # =========================
    (
        "Manual Uploads - Saved Documents",
        "manual_upload",
        "manual_document",
        5,
        "file://data/raw/manual_uploads",
        "Local manually uploaded documents such as permitted PDFs, transcripts, articles, or analyst notes for controlled POC ingestion.",
        ["Nvidia"],
        ["industry_context", "risk_factors", "supplier_dependency", "competitor_movement"],
        0.60,
        "unknown",
        "manual_only",
        "manual_upload",
        "manual_only",
        "manual",
        ["pdf", "txt", "html"],
        3,
        ["graph_context", "watch_item_generation"],
        "Manual-only. Requires human review."
    ),
    (
        "Manual Uploads - Earnings Call Transcripts",
        "manual_upload",
        "earnings_call_transcript",
        5,
        "file://data/raw/transcripts",
        "Manually saved earnings call transcripts when official or licensed transcript access is available.",
        ["Nvidia", "TSMC", "SK Hynix", "Micron", "AMD"],
        ["financial_performance", "data_center_growth", "hbm_supply", "competitor_movement"],
        0.70,
        "unknown",
        "manual_only",
        "manual_upload",
        "manual_only",
        "quarterly",
        ["txt", "transcript", "pdf"],
        3,
        ["evidence_extraction", "relationship_discovery", "event_detection"],
        "Only use if transcript rights are clear."
    )
]


def main():
    sources = []
    for idx, row in enumerate(SOURCE_ROWS, start=1):
        sources.append(make_source(idx, *row))

    registry = {
        "registry_version": "0.1.0",
        "registry_name": "Nvidia Source Registry",
        "primary_entity": "Nvidia",
        "description": (
            "Trusted source registry for Phase 1 of the Nvidia Intelligence POC. "
            "The registry is intentionally broad, while active ingestion remains narrow and high-signal."
        ),
        "sources": sources
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)

    print(f"Created {OUTPUT_PATH} with {len(sources)} sources.")


if __name__ == "__main__":
    main()